"""
Synthetic heightmap generator for the 3D terrain viewer.

HONESTY NOTE: the implementation plan (Section 6.3) specifies fetching a
real DEM tile from OpenTopography for the region covering all 6 pilot
sites. That requires an OpenTopography API key and outbound network
access to portal.opentopography.org, neither of which is available in
this build sandbox (network here is allowlisted to package registries
only). What this script produces instead is a PHYSICALLY PLAUSIBLE
SYNTHETIC terrain -- built from layered noise plus deliberate ridge/valley
structure roughly matching North Sikkim's real elevation range (600m-4200m,
per demo/pilot_locations.json) -- NOT real elevation data for these
coordinates.

The dashboard must show a visible "Synthetic terrain (replace with real
DEM before presenting)" label as long as this synthetic heightmap is in
use -- do not present this as real DEM data to judges. See
terrain3d/fetch_dem.py for the real-data swap-in, which needs only an
OpenTopography API key to run for real once your team has network access.
"""

from __future__ import annotations

import json
import math
import os
import random

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GRID_SIZE = 128  # 128x128 heightmap, enough detail for an orbitable demo mesh
REGION_BOUNDS = {"south": 27.05, "north": 27.75, "west": 88.45, "east": 88.80}


def _load_pilot_locations():
    with open(os.path.join(REPO_ROOT, "demo", "pilot_locations.json")) as f:
        return json.load(f)["locations"]


def _fractal_noise(x, y, seed, octaves=5):
    """Simple layered sine-based noise -- not a real terrain algorithm
    (e.g. not Perlin/Simplex), but sufficient to produce non-repeating,
    plausible-looking ridges for a visualization, without adding a noise
    library dependency."""
    rng = random.Random(seed)
    phases = [(rng.uniform(0, 6.28), rng.uniform(0, 6.28)) for _ in range(octaves)]
    value = 0.0
    amplitude = 1.0
    freq = 1.0
    total_amplitude = 0.0
    for i, (px, py) in enumerate(phases):
        value += amplitude * math.sin(x * freq + px) * math.cos(y * freq + py)
        total_amplitude += amplitude
        amplitude *= 0.5
        freq *= 2.1
    return value / total_amplitude


def generate_region_heightmap(seed: int = 7) -> dict:
    locations = _load_pilot_locations()
    lat_range = REGION_BOUNDS["north"] - REGION_BOUNDS["south"]
    lon_range = REGION_BOUNDS["east"] - REGION_BOUNDS["west"]

    heights = []
    for j in range(GRID_SIZE):
        for i in range(GRID_SIZE):
            nx = i / GRID_SIZE * 4.0
            ny = j / GRID_SIZE * 4.0
            base_noise = _fractal_noise(nx, ny, seed)

            # Bias elevation higher toward the north (Lachung/Lachen direction,
            # consistent with North Sikkim's real geography where the
            # Himalayan high country is north of Gangtok) -- a coarse,
            # deliberately-simple realism cue, not derived from real data.
            north_bias = (j / GRID_SIZE) * 0.6

            elevation_0_1 = max(0.0, min(1.0, 0.4 + 0.35 * base_noise + north_bias * 0.3))
            elevation_m = 500 + elevation_0_1 * 3800  # spans ~500m-4300m, matching real NER range
            heights.append(round(elevation_m, 1))

    site_markers = []
    for loc in locations:
        u = (loc["longitude"] - REGION_BOUNDS["west"]) / lon_range
        v = (loc["latitude"] - REGION_BOUNDS["south"]) / lat_range
        grid_x = int(max(0, min(GRID_SIZE - 1, u * GRID_SIZE)))
        grid_y = int(max(0, min(GRID_SIZE - 1, v * GRID_SIZE)))
        site_markers.append({
            "location_id": loc["location_id"],
            "name": loc["name"],
            "grid_x": grid_x,
            "grid_y": grid_y,
            "latitude": loc["latitude"],
            "longitude": loc["longitude"],
            "elevation_m": heights[grid_y * GRID_SIZE + grid_x],
        })

    return {
        "data_provenance": "SYNTHETIC — generated by terrain3d/generate_synthetic_heightmap.py, "
                            "NOT real DEM data for these coordinates. See module docstring.",
        "grid_size": GRID_SIZE,
        "bounds": REGION_BOUNDS,
        "heights": heights,
        "site_markers": site_markers,
    }


if __name__ == "__main__":
    out_dir = os.path.join(REPO_ROOT, "terrain3d", "heightmaps")
    os.makedirs(out_dir, exist_ok=True)
    data = generate_region_heightmap()
    out_path = os.path.join(out_dir, "north_sikkim_region_heightmap.json")
    with open(out_path, "w") as f:
        json.dump(data, f)
    print(f"Generated synthetic heightmap: {len(data['heights'])} points, "
          f"{len(data['site_markers'])} site markers")
    print(f"Saved to {out_path}")
    for s in data["site_markers"]:
        print(f"  {s['location_id']}: grid=({s['grid_x']},{s['grid_y']}) elevation={s['elevation_m']}m")
